# Generated by Django 3.0.1 on 2019-12-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191221_1015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('item', 'user')},
        ),
    ]
